name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./LichessApi/
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./LichessApi/
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./LichessApi/
